name: Home Page CSS Changing

on:
  schedule:
    - cron: "*/13 * * * *"   # Har 15 minute par chalega
  workflow_dispatch:         # Manual run allowed

jobs:
  ping_site:
    runs-on: ubuntu-latest

    steps:
      - name: Call website URL to refresh
        run: |
          curl -X GET "https://satamatkas.com/adminarea/homepage/changecss.php"
