name: Panel 2 Fetching

on:
  schedule:
    - cron: "*/17 * * * *"   # Har 15 minute par chalega
  workflow_dispatch:         # Manual run allowed

jobs:
  ping_site:
    runs-on: ubuntu-latest

    steps:
      - name: Call website URL to refresh
        run: |
          curl -X GET "https://satamatkas.com/adminarea/recordfetch/panel_fetch2.php"
