name: Smart Link 1

on:
  schedule:
    - cron: "*/17 * * * *"   # Har 15 minute par chalega
  workflow_dispatch:         # Manual run allowed

jobs:
  ping_site:
    runs-on: ubuntu-latest

    steps:
      - name: Call website URL to refresh
        run: |
          curl -X GET "https://www.effectivegatecpm.com/xe3mva99c?key=777e1cf3747905db7664de0e36532101"
